version: "3.3"
services:
 apache:
   image: httpd:latest
   ports:
      - 8000:80
   volumes:
     - confapache:/usr/local/apache2/conf
     - htdocs:/usr/local/apache2/htdocs
   networks:
      red:
        ipv4_address: 10.5.0.5
 apache-cliente:
   image: kasmweb/desktop:1.10.0
   ports:
      - 6901:6901
   stdin_open: true  # docker run -i
   tty: true         # docker run -t
   environment:
    - VNC_PASSWORD=password # contraseña en string
   networks:
      red:
        ipv4_address: 10.5.0.3
 bind9:
    container_name: bind9_server
    image: internetsystemsconsortium/bind9:9.16
    networks:
      red:
        ipv4_address: 10.5.0.2
    ports:
      - 801:801
    volumes:
      - bind:/etc/bind
 wireshark:
    image: linuxserver/wireshark:latest
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /usr/local/wireshark/config
    ports:
      - 3000:3000
    restart: unless-stopped      
networks:
  red:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  bind:
   external: true
  confapache: 
   external: true
  htdocs:
   external: true