version: "3.3"
services:
 apache:
   image: httpd:latest
   ports:
      - 800:800
   volumes:
     - conf:/usr/local/apache2/conf
     - htdocs:/usr/local/apache2/htdocs
   networks:
      red:
        ipv4_address: 10.5.0.5
 apache-cliente:
   image: kasmweb/desktop:1.10.0
   ports:
      - 6901:6901
   stdin_open: true  # docker run -i
   tty: true         # docker run -t
   environment:
    - VNC_PASSWORD=password # contraseña en string
   networks:
      red:
        ipv4_address: 10.5.0.3
 bind9:
    container_name: bind9_server
    image: internetsystemsconsortium/bind9:9.16
    networks:
      red:
        ipv4_address: 10.5.0.2
    ports:
      - 801:801
    volumes:
      - bind:/etc/bind

networks:
  red:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  bind:
   external: true
  conf: 
   external: true
  htdocs:
   external: true